[General]
device_name = 'device2'
client_privilege = 3
node_name='device2_last_test3'
device_id = '(0,0)'

[HOS_server]
HOS_available=true
server_url = 'hos.seonhunlee.me'
port =  5051

[Weights]
label_name='label_list.pkl'
model_name='trained_model3.h5'

[Output]
output_csv_fname = 'device2_data'